// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	Username        sql.NullString `json:"username"`
	MagicToken      sql.NullString `json:"magic_token"`
	TokenExpiration sql.NullTime   `json:"token_expiration"`
}
