// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type User struct {
	ID              int32          `json:"id"`
	Email           string         `json:"email"`
	MagicToken      sql.NullString `json:"magic_token"`
	TokenExpiration sql.NullTime   `json:"token_expiration"`
}
